### ISSUE TITLE
直接下载你的代码，报TypeError

### ISSUE THREAD

**Issue by lulu27753** [simonguo/react-code-view#1]
![image](https://user-images.githubusercontent.com/20608421/47137924-95128800-d2ea-11e8-88bb-7e2d4944f899.png)

**Comment by ladyzdp** [comment]
webpack.config.js 中  markdownRenderer应该是方法；


`{
        loader: 'markdown-loader',
        options: {
          pedantic: true,
          renderer: markdownRenderer()
        }
      }`

**Comment by simonguo** [comment]
是的 , `markdownRenderer` 在 `react-markdown-reader` 1.1.0 版本中我改成了 function , 为了可以传递支持的语言。 

这样做的目的是为了打包的时候不至于把所有的语言支持包都打进去，需要支持什么语言就在通过 markdownRenderer(['javascript']) 传递进入。

默认值是: ["javascript", "bash", "xml", "css", "markdown", "less"]

**Comment by simonguo** [comment]
Fix: https://github.com/simonguo/react-code-view/commit/da83ac8a78c1c48f70514cdaf92175a5fc7de25b

**Comment by ladyzdp** [comment]
您好：

插件非常棒！
目前在使用这个插件生成项目文档，我们用的是tsx结尾的文件，生成的页面没有样式和代码块，想问您一下我需要如何设置才能支持tsx的解析呢？😊


Simon Guo <notifications@github.com> 于2018年11月8日周四 上午10:09写道：

**Comment by simonguo** [comment]
@sassplus  没有样式，你 import less 了没？
```
import 'react-code-view/lib/less/index.less';
```

**Comment by ladyzdp** [comment]
感谢，样式没有出来是因为没有导入样式，现在已经好了。😊

Simon Guo <notifications@github.com> 于2018年11月8日周四 下午10:35写道：

**Comment by simonguo** [comment]
升级到最新版本 [react-code-view@2.0.0](https://github.com/simonguo/react-code-view/releases/tag/2.0.0)。
- 重写了 markdown-loader ，不需要引入多个 loader
- 不需要额外引入 babel
