### ISSUE TITLE
是否有计划升级 babel 到 17 版本

### ISSUE THREAD

**Issue by MuYunyun** [simonguo/react-code-view#27]
请问楼主是否有计划升级 Babel 版本到 7 https://unpkg.com/@babel/standalone@7.16.3/babel.min.js ，以使用到与 React 相关的新特性。

https://github.com/simonguo/react-code-view/blob/master/docs/index.html#L10

**Comment by simonguo** [comment]
babel 17 ?   

在你的项目中直接把 cdn 改为 babel 7 的地址就行， 另外可以通过 `babelTransformOptions ` 修改配置

```jsx
<CodeView babelTransformOptions={{  presets: ['stage-0', 'react', 'es2015'] }} >
```

**Comment by MuYunyun** [comment]
> ```js
> babelTransformOptions
> ```

我试了下直接修改 cdn 为 https://unpkg.com/@babel/standalone@7.16.3/babel.min.js 不太行，babelTransformOptions 传入的配置貌似有点差异，目前还没跑通，等空了我再试试。

**Comment by MuYunyun** [comment]
我试了下直接修改 cdn 为 https://unpkg.com/@babel/standalone@7.16.3/babel.min.js 不太行，babelTransformOptions 传入的配置貌似有点差异，目前还没跑通，等空了我再试试。

**Comment by simonguo** [comment]
@MuYunyun  升级到最新版本 react-code-view@2.0.0，不需要额外引入 babel 。 
内置了 `@swc/wasm-web`  对代码进行转换。
