### ISSUE TITLE
next.js 编译的时候会报错

### ISSUE THREAD

**Issue by fortune-cook1e** [simonguo/react-code-view#43]
版本信息：
```javascript
  "next": "13.3.0",
  "react": "18.2.0",
  "react-code-view": "^2.2.1",
  "react-dom": "18.2.0",
```

在next.js 项目执行 `build` 命令时会报如下错误
![image](https://user-images.githubusercontent.com/29733380/236804002-43be9987-bed2-4380-978d-4ac268482ef4.png)

报错代码：
![image](https://user-images.githubusercontent.com/29733380/236804058-ed7ce849-4c06-421e-97ae-61fbf2c9407b.png)

**Comment by simonguo** [comment]
服务端渲染肯定找不到 document ，你可以在渲染 CodeView 前加一个 `canUseDOM` 判断。

rsuite 也用的是 nextjs，参考: https://github.com/rsuite/rsuite/blob/main/docs/components/CodeView/CodeView.tsx#L181

**Comment by fortune-cook1e** [comment]
> 服务端渲染肯定找不到 document ，你可以在渲染 CodeView 前加一个 `canUseDOM` 判断。
> 
> rsuite 也用的是 nextjs，参考: https://github.com/rsuite/rsuite/blob/main/docs/components/CodeView/CodeView.tsx#L181

好的 非常感谢！
