### ISSUE TITLE
一个md文件，怎么渲染多个code段

### ISSUE THREAD

**Issue by yangguangyu** [simonguo/react-code-view#7]
我看rsuite的文档是可以多个渲染的，请问是怎么实现的，难道是要创建多个md文件 https://rsuitejs.com/en/components/dropdown 任意一个组件基本都是多个代码段的

**Comment by simonguo** [comment]
@yangguangyu  对，多个文件
https://github.com/rsuite/rsuite.github.io/tree/master/src/pages/components

**Comment by simonguo** [comment]
@yangguangyu  升级到 react-code-view@2.1.0 支持渲染多个code段。https://github.com/simonguo/react-code-view/pull/35
